### ISSUE TITLE
Empty audio not displayed even with Should Draw Silence 

### ISSUE THREAD

**Issue by ShivamRawat0l** [dmrschmidt/DSWaveformImage#71] opened 2023-06-02 13:31 UTC
![Screenshot 2023-06-02 at 7 03 50 PM](https://github.com/dmrschmidt/DSWaveformImage/assets/27425384/7b250b0a-dea2-4227-9b2c-a8da03b6b5a6)

```
                    if(data.count > 0) {
                            WaveformLiveCanvas(samples: [],configuration: liveConfiguration,
                                       renderer: LinearWaveformRenderer(),
                                       shouldDrawSilencePadding: true)
                    }
             
               
                WaveformLiveCanvas(samples: [],configuration: liveConfiguration,
                                   renderer: LinearWaveformRenderer(),
                                   shouldDrawSilencePadding: true)
            
```

This is the code. Second one is working and giving drawing the silence. But for the first one it is waiting for the data to be fetched from the internet and then it is showing WaveformLiveCanvas. If I give some values in the first samples then it will display it correctly. Just not the silent part. 

I am new to swift so might be missing something. 

I also tried making the `shouldDrawSilencePadding  : state ` assign it to state and making the state false at first. 
Then setting 
`state = true ` wont update it but 
`state = !state` will do after some clicks don't know why.

**Comment by dmrschmidt** [comment] 2023-06-02 16:28
Hey @ShivamRawat0l,

I took a quick look at this myself and I can reproduce the behavior you describe.

I cannot yet exactly say why, but it does seem to be a bug in the state handling of WaveformLiveCanvas.

I’ll look into this further, but can’t promise when I may have found a fix for this.

So in the meantime your workaround will have to do. IMHO that looks like a perfectly fine and even simpler approach anyway, no?

Out of curiosity - not sure whether this is related to the library at all - what error are you getting with List?

**Comment by dmrschmidt** [comment] 2023-06-02 16:57
Ah ok, I think I get what you mean.

In any case, I think I've found and fixed the issue.
If I'm completely honest with you, I don't 100% understand **why** SwiftUI behaves the way it does here. Something about `@StateObject` that behaves different to what I'd expect.

Update to [13.0.1](https://github.com/dmrschmidt/DSWaveformImage/releases/tag/13.0.1) and the issue should be fixed. Please let me know if it does / doesn't.

**Closed as completed** 2023-06-02 19:32 UTC
